= Jason
:icons: font

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

ifdef::env-github[:outfilesuffix: .adoc]

Jason is an interpreter for an extended version of AgentSpeak. It implements the operational semantics of that language, and provides a platform for the development of multi-agent systems, with many user-customisable features. Jason is available as Open Source, and is distributed under GNU LGPL.

Jason is developed by http://https://jomifred.github.io[Jomi F. Hübner] and http://www.inf.pucrs.br/r.bordini[Rafael H. Bordini], based on previous work done with many colleagues, in particular Michael Fisher, Joyce Martins, Álvaro Moreira, Renata Vieira, Willem Visser, Mike Wooldridge, but also many others, as acknowledged in the manual (see the http://jason.sourceforge.net/wp/documents/[documents] page).

== Documentation

Most of the Jason documentation is available link:doc/readme{outfilesuffix}[in the doc folder].

== Installation

=== For Jason users

- get a release https://sourceforge.net/projects/jason/files/jason/[here]
// - install the eclipse plugin as described http://jacamo.sourceforge.net/eclipseplugin/tutorial[here] or configure your shell command as described http://jacamo.sourceforge.net/tutorial/hello-world/shell-based.html[here]
- follow the link:doc/tutorials/getting-started/readme{outfilesuffix}[getting started tutorial]
- more documentation http://jason.sourceforge.net/wp/documents[here]

NOTE: In Jason 3.2 no IDE is included in Jason distribution. A command line interpreter is now provided.

=== For Jason developers

----
git clone --recursive https://github.com/jason-lang/jason.git
cd jason
git checkout develop  // <3>
git submodule update --init --recursive	// <3>
./gradlew config // <1> <2>
----
<1> the config task builds the JasonCLI (Jason Command Line Interface).
<2> this task also prints out the commands to set up the `JASON_HOME` and `PATH` variables.
<3> optional if you want to use the develop branch.

Examples can be run using the `jason` command, for example:

	cd examples/domestic-robot
	jason DomesticRobot.mas2j 

Other useful gradle tasks:

-----
./gradlew jar     // <1>
./gradlew doc     // <2>
./gradlew clean   // <3>
./gradlew release // <4>
-----
<1> generates a new jason jar.
<2> generates the javadoc and transforms asciidoc files into html (Docker must be running for the latter).
<3> cleans all generated files.
<4> produces a zip file in `build/distributions` to be distributed to users.

You can use your IDE to change the Jason implementation by importing the Gradle project.
