= Annotations in Jason
:toc: right
:source-highlighter: coderay
:coderay-linenums-mode: inline
:icons: font
:prewrap!:

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]


ifdef::env-github[:outfilesuffix: .adoc]

== Introduction

Jason has a set of tools for testing Jason agents which includes a test management engine, a tester agent skeleton and plans for assertion checks.

The test library is written and interpreted by Jason.

This test facilities can be used both using the management engine or as a simple library.

== The test management engine

Jason provides an infrastructure to add testing agents to be launched in tests, which allows, for instance, continuous integration tests for Jason agents.

The test management engine is launched by `$ gradle test` command. It will launch all tester agents presented in the default test folder for asl files.

In case of any assertion fails the exit status will inform failure to the operation system. If all tests pass, the exit status is normal, meaning success. These status inform integration tools (e.g. circle CI, github actions) about the results of tests.

The default command `$ gradle test` prints only `warning` and `several` log messages. It also supports `$ gradle test --info` which besides higher levels also prints `info` messages (which include the .print internal action). For even more deailed output `$ gradle test --debug` can be used.

Jason tests is a NOT cacheable gradle task which means it runs completely every time and no clean command is needed.

The tester agents that imports the skeleton `tester_agent.asl` are equipped with the test library such as assertion plans.

== Using the test engine

1. Create an agent for testing your agent(s) in the folder `src/test/jason/asl` (all agents in this folder are automatically launched in the test task).
2. Make your agent a tester agent including `tester_agent.asl` skeleton
 ```
 { include("tester_agent.asl") }
 ```
3. Add to your test agent support to the agent it is going to test, eg:
  ```
 { include("bob.asl") }
  ```
4. Activate auto execution of plans labeled with `test`
 ```
 !execute_test_plans.
 ```
5. Run `gradle test` to check the results.

=== Example

Let us say we have an agent `bob` which has a rule to sum to numbers. We want to check if bob can make correct sums. The content of `bob.asl` is:
----
sum(X,Y,R):-R = X + Y.
----

To test it, we can create a tester agent following the steps above. The content of `src/test/jason/asl/test_bob.asl` can be:

----
{ include("tester_agent.asl") }
{ include("bob.asl") }

!execute_test_plans.

@test_sum[atomic]
+!test_sum :
    true
    <-
    ?sum(1.3,2.6,R);
    !assert_equals(3.9,R,0.1);
.
----

== The library

The library provides assertion plans, which can be found in `test_assert.asl` file.

An alternative use of the test tools is to do not use the management engine, instead, just include `test_assert.asl` to any agent. The results for assertions will be displayed as ordinary printed messages generated by the agent.
