#!/bin/bash

P=`which "$0"`
source "`dirname $P`/jason-setup"

JEDIT_HOME=$JASON_HOME/jedit

systemName="$(uname -s)"
case "${systemName}" in
    CYGWIN*)    os=win;;
    MINGW*)     os=win;;
    *)          os=nix
esac

if [ ${os} == "win" ]; then
  CP="$JEDIT_HOME/jedit.jar;$JEDIT_HOME/jars/ErrorList.jar;$JEDIT_HOME/jars/SideKick.jar;$JADE_JAR;$JASON_HOME/libs/*"
else
  CP="$JEDIT_HOME/jedit.jar:$JEDIT_HOME/jars/ErrorList.jar:$JEDIT_HOME/jars/SideKick.jar:$JADE_JAR:$JASON_HOME/libs/*"
fi

# run jIDE
java \
-classpath $CP \
   org.gjt.sp.jedit.jEdit $1
