#!/bin/sh

# generate .dot files to build a map of goals (using http://www.graphviz.org/)

CURDIR=`pwd`
JASON_HOME=`dirname $0`
cd "$JASON_HOME/.."
JASON_HOME=`pwd`
cd $CURDIR

java -classpath "$JASON_HOME/lib/jason.jar" jason.util.asl2dot $1
