#!/bin/bash

source "`dirname "$0"`/jason-setup"

JEDIT_HOME=$JASON_HOME/jedit

systemName="$(uname -s)"
case "${systemName}" in
    CYGWIN*)    os=win;;
    MINGW*)     os=win;;
    *)          os=nix
esac

if [ ${os} == "win" ]; then
  CP="$JASON_JAR;$JEDIT_HOME/jedit.jar;$JEDIT_HOME/jars/ErrorList.jar;$JEDIT_HOME/jars/SideKick.jar;$JADE_JAR"
else
  CP="$JASON_JAR:$JEDIT_HOME/jedit.jar:$JEDIT_HOME/jars/ErrorList.jar:$JEDIT_HOME/jars/SideKick.jar:$JADE_JAR"
fi

# run jIDE
java \
-classpath $CP \
   org.gjt.sp.jedit.jEdit $1
