#!/bin/bash

if [ -z $JASON_HOME ] ; then
    CURDIR=`pwd`
    JASON_HOME=`dirname $0`
    cd "$JASON_HOME/.."
    JASON_HOME=`pwd`
    cd $CURDIR
fi

if [ -z $JDK_HOME ] ; then
    if [ -n $JAVA_HOME ] ; then
	    JDK_HOME=$JAVA_HOME
    fi
fi

# check JDK_HOME
if [ ! -f $JDK_HOME/bin/javac ] ; then
   echo JDK_HOME is not properly set!
fi

JASON_JAR=`find $JASON_HOME/libs -name jason-2*.jar`
JEDIT_HOME=$JASON_HOME/jedit
JADE_JAR=`find $JASON_HOME/libs -name jade*.jar`

# run jIDE
$JDK_HOME/bin/java \
-classpath $JASON_JAR:$JEDIT_HOME/jedit.jar:$JEDIT_HOME/jars/ErrorList.jar:$JEDIT_HOME/jars/SideKick.jar:$JADE_JAR \
   org.gjt.sp.jedit.jEdit $1
