#!/bin/bash
#
# this script creates the Ant script (build.xml)
# to run a Jason project
#

if [ ! -f $1 ]
then
    echo File $1 not found
    exit
fi

source `dirname $0`/jason-setup

java -cp $JASON_JAR:$JADE_JAR jason.mas2j.parser.mas2j $1 $2
