name: Java CI

on: [push, pull_request]

jobs:
  validate-gradle-wrapper:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: gradle/actions/wrapper-validation@v4

  build:
    needs: validate-gradle-wrapper
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [21]

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java-version }}
        cache: 'gradle'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Test java
      run: ./gradlew :jason-interpreter:test
    - name: Test jason
      run: ./gradlew :jason-interpreter:testJason
